spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/profile-database
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #dialect: org.hibernate.dialect.
        #show-sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
  #org.hibernate.type: true

cloud:
  aws:
    s3:
      bucket: 
    credentials:
      access-key:
      secret-key:
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false